### ISSUE TITLE
Menu options are not dark-themed

### ISSUE THREAD

**Issue by dulldesk** [winghongchan/dark-docs#20]
As the title says, evident on Firefox v11.0.1 when clicking on the File, Edit, etc. menu options. May be a result of #16. 

The following seems to largely help fix it on my end, though the colour variables are likely inconsistent and it is not in LESS/UserCSS syntax. I'm happy to make a pull request to properly patch it much later this month (as it is exam season for me). 

```css
.goog-menu {
  background: var(--ddocs-surface-container-high);
}

.docs-gm .goog-menuitem {
  color: var(--ddocs-on-surface);
}

.docs-gm .goog-menuitem-highlight {
  background-color: var(--ddocs-on-background-pressed);
}

.goog-menuitem-highlight .goog-menuitem-content, .goog-menuitem-hover .goog-menuitem-content {
  color: var(--ddocs-on-surface);
}

.docs-material.goog-menu .apps-menuitem .goog-menuitem-checkbox, .docs-material.goog-menu .apps-menuitem .goog-menuitem-icon {
  filter: var(--ddocs-primary-icon);
}

.goog-option-selected .goog-menuitem-content {
  color: inherit;
}
```
