### ISSUE TITLE
The paragraph styles menu is illegible

### ISSUE THREAD

**Issue by winghongchan** [winghongchan/dark-docs#4]
The menu background is dark, but the font colors are not inverted to match.

**Comment by winghongchan** [comment]
```css
.goog-menu-vertical .goog-menuitem-label /* Mostly for the styles picker */ {
  color: white !important;
}
```
